
export default [
    {
        name:'图片',
        type:'img',
        tag:'img',
        icon:'icon-image1',
        props:{
            src:'https://avatars.githubusercontent.com/u/59641156?v=4',
            draggable:false
        },
        style:{
            width:'100%',
            height:'100%'
        },
        formId:'c0c67e96-858b-4303-999c-92d0d39cb792'
    },
    {
        name:'文本',
        type:'text',
        tag:'span',
        icon:'icon-text',
        props:{
            value:'text'
        }
    },
    {
        name:'视频',
        type:'video',
        tag:'video',
        icon:'icon-video',
        props:{
            src:'',
            controls:true,
            draggable:false
        },
        style:{
            width:'100%',
            height:'100%',
            'object-fit':'fill',
            'z-index':-1
        }
    },{
        name:'嵌入页',
        type:'iframe',
        tag:'iframe',
        icon:'icon-HTML',
        props:{
            src:'http://120.26.161.36:8080/',
            draggable:false
        },
        style:{
            width:'100%',
            height:'100%',
            'z-index':-1
        }
    }
]